### ISSUE TITLE
Error after 'Clear cache'

### ISSUE THREAD

**Issue by Devanathur** [multimerch/theme-compatibility#10]
Hi,

On the fresh installation of opencart, when I install multimerch, it works fine.
{Latest versions of all --opencart, multimerch, journal, and a fix for 'Journal with multimerch' { https://github.com/airnayden/theme-compatibility/tree/patch-7 } }

But as I install Journal theme it gives error on 'clear cache' . The whole site collapses

Would be grateful for any of your help.

Not able to attach screenshot so copy pasting errors on admin panel............

Notice: Undefined property: Loader::$load in K:\Nirav\opencart\site\vqmod\vqcache\vq2-admin_view_template_common_header.tpl on line 96
( ! ) Fatal error: Call to a member function model() on a non-object in K:\Nirav\opencart\site\vqmod\vqcache\vq2-admin_view_template_common_header.tpl on line 96
Call Stack
#	Time	Memory	Function	Location
1	0.0012	306320	{main}( )	..\index.php:0
2	0.0700	2044552	Front->dispatch( )	..\index.php:178
3	0.0745	2132896	Front->execute( )	..\vq2-system_engine_front.php:63
4	0.0745	2132896	Action->execute( )	..\vq2-system_engine_front.php:89
5	0.0767	2380344	call_user_func ( )	..\vq2-system_engine_action.php:46
6	0.0767	2380376	ControllerExtensionModification->index( )	..\vq2-system_engine_action.php:46
7	0.0795	2415480	ControllerExtensionModification->getList( )	..\modification.php:17
8	0.0833	2489448	Loader->controller( )	..\modification.php:777
9	0.0847	2564312	call_user_func ( )	..\vq2-system_engine_loader.php:55
10	0.0847	2564344	ControllerCommonHeader->index( )	..\vq2-system_engine_loader.php:55
11	0.1216	4775336	Loader->view( )	..\vq2-admin_controller_common_header.php:141
12	0.1232	5037160	require( 'K:\Nirav\opencart\site\vqmod\vqcache\vq2-admin_view_template_common_header.tpl' )	..\vq2-system_engine_loader.php:93
----------------------------------------------------------------------------------------------------------
Copy pasting error on site after clear cache

Journal Installation Error

Access OpenCart Modifications Page and hit the Refresh button. See example.

**Comment by ffctcc** [comment]
What version of vQmod do you have installed and where did you install it from? You need to have the latest "vQmod for OpenCart" from vqmod.com.

Versions of vQmod installed through other means (opencart.com marketplace or vQmod managers or all sorts) are known to have compatibility issues with OpenCart's OCMOD and thus with third party themes/plugins.

**Comment by Devanathur** [comment]
Installed vqmod v2.5.1-opencart from
https://github.com/vqmod/vqmod/releases
The above link is re-directed from the url http://vqmod.com/

**Comment by ffctcc** [comment]
Could you mail us your admin-area and FTP accesses to support@multimerch.com so we could test this? This doesn't happen on our development OC/MM/Journal setup (that we use to create/test Journal patches) so it must be something else.

**Comment by Devanathur** [comment]
Hi,

Mail sent with all details to support@multimerch.com

**Comment by Devanathur** [comment]
Hope it could get resolved. Please let me know any feedbacks..
